# Generated by Django 4.2.23 on 2025-07-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_campus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='campus',
            new_name='Location',
        ),
    ]
