# Generated by Django 4.2.23 on 2025-07-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_professor_rename_location_location_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(to='main_app.professor'),
        ),
    ]
